### ISSUE TITLE
Documentation is incomplete

### ISSUE THREAD

**Issue by tarslangil** [aronbalog/Vox#2]
Hello,

Thanks for the library.

let dataSource = DataSource<ClientEvent>(strategy: .path("<type>/<id>"), client: client)

I'm trying to create a request but i still can't find what the "client" must be?The documentation is incomplete and can't find any information about it.

Best,

**Comment by aronbalog** [comment]
@tarslangil Thanks for the report.
Docs are updated along with minor interface changes. Also, Alamofire support is added. Please check [this link](https://github.com/aronbalog/Vox#client-protocol).
