### ISSUE TITLE
Support for custom request with userInfo

### ISSUE THREAD

**Issue by JFejza** [aronbalog/Vox#3]
Add userInfo dictionary for custom configuration of request

**Comment by aronbalog** [comment]
It would be better if we call `executeRequest` with `userInfo` argument instead of `Request`. As `Request` is an internal object (sort of), it could be confusing for others to see request in Client implementation.

**Comment by JFejza** [comment]
Sure, I agree, I'll change it and update the PR

**Comment by JFejza** [comment]
Updated PR

**Comment by aronbalog** [comment]
Merged.
